"""migration1

Revision ID: 7a006bb278ad
Revises: 4d038f83e4ba
Create Date: 2025-04-11 00:09:44.920428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a006bb278ad'
down_revision = '4d038f83e4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_private_key', sa.Text(), nullable=True))
        batch_op.drop_column('peer_private_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_private_key', mysql.VARCHAR(length=5000), nullable=True))
        batch_op.drop_column('ssh_private_key')

    # ### end Alembic commands ###
